site_name: "TMPT"

form_fields:
  category: "type"
  medium: "medium_sel[4]"
  video_codec: "codec_sel[4]"
  audio_codec: "audiocodec_sel[4]"
  resolution: "standard_sel[4]"
  team: "team_sel[4]"
  tags[]: "tags[4][]"

source_parsers:
  source_params:
    type:
      source_key: "类型"
    medium:
      source_key: "媒介"
    video_codec:
      source_key: "视频编码"
    audio_codec:
      source_key: "音频编码"
    resolution:
      source_key: "分辨率"
    team:
      source_key: "制作组"
    tag:
      source_key: "标签"

  standard_keys:
    type:
      "电影": "category.movie"
      "电视剧": "category.tv_series"
      "综艺": "category.tv_shows"
      "纪录片": "category.documentaries"
      "动漫": "category.animation"
      "MV": "category.mv"
      "体育": "category.sports"
      "音频": "category.audio"
      "音乐": "category.music"
      "其他": "category.other"
      "短剧": "category.playlet"

    medium:
      "Other": "medium.other"
      "Track": "medium.track"
      "CD": "medium.cd"
      "DVD": "medium.dvd"
      "HDTV": "medium.hdtv"
      "WEB-DL": "medium.webdl"
      "Encode": "medium.encode"
      "Remux": "medium.remux"
      "Blu-ray": "medium.bluray"
      "UHD Blu-ray": "medium.uhd_bluray"

    video_codec:
      "H.264/AVC": "video.h264"
      "H.265/HEVC": "video.h265"
      "VC-1": "video.vc1"
      "MPEG-2": "video.mpeg2"
      "AV1": "video.av1"
      "Other": "video.other"

    audio_codec:
      "ALAC": "audio.alac"
      "AAC": "audio.aac"
      "APE": "audio.ape"
      "TrueHD Atmos": "audio.truehd_atmos"
      "DDP/E-AC3": "audio.ddp"
      "DD/AC3": "audio.ac3"
      "LPCM": "audio.lpcm"
      "TrueHD": "audio.truehd"
      "DTS:X": "audio.dtsx"
      "DTS-HD MA": "audio.dts_hd_ma"
      "DTS": "audio.dts"
      "M4A": "audio.m4a"
      "WAV": "audio.wav"
      "MP3": "audio.mp3"
      "FLAC": "audio.flac"
      "Other": "audio.other"

    resolution:
      "480p/480i": "resolution.r480p"
      "720p/720i": "resolution.r720p"
      "1080p/1080i": "resolution.r1080p"
      "4K/2160p/2160i": "resolution.r2160p"
      "8K/4320p/4320i": "resolution.r4320p"
      "Other": "resolution.other"

    team:
      "HDS": "team.hds"
      "CHD": "team.chd"
      "MySiLU": "team.mysilu"
      "WiKi": "team.wiki"
      "Other": "team.other"
      "rain": "team.rain"
      "rainweb": "team.rainweb"
      "Tangweb": "team.tangweb"
      "TangPT": "team.tangpt"

    tag:
      "特效": "tag.特效"
      "杜比": "tag.杜比"
      "禁转": "tag.禁转"
      "首发": "tag.首发"
      "粤语": "tag.粤语"
      "DIY": "tag.DIY"
      "国语": "tag.国语"
      "中字": "tag.中字"
      "HDR": "tag.HDR"
      "Remux": "tag.Remux"
      "合并": "tag.合并"
      "超分": "tag.超分"
      "大包": "tag.大包"
      "应求": "tag.应求"
      "完结": "tag.完结"
      "分集": "tag.分集"
      "英字": "tag.英字"
      "韩剧": "tag.韩剧"

mappings:
  type:
    "category.movie": "401"
    "category.tv_series": "402"
    "category.tv_shows": "403"
    "category.documentaries": "404"
    "category.animation": "405"
    "category.mv": "406"
    "category.sports": "407"
    "category.audio": "408"
    "category.music": "408"
    "category.hq_audio": "408"
    "category.audiobook": "408"
    "category.other": "409"
    "category.books": "409"
    "category.playlet": "410"
    "category.micro_drama": "410"
    "default": "409"

  medium:
    "medium.uhd_bluray": "10"
    "medium.bluray": "11"
    "medium.remux": "12"
    "medium.encode": "13"
    "medium.webdl": "14"
    "medium.hdtv": "15"
    "medium.dvd": "16"
    "medium.cd": "17"
    "medium.track": "18"
    "medium.other": "19"
    "default": "19"

  video_codec:
    "video.h264": "6"
    "video.h265": "7"
    "video.vc1": "8"
    "video.mpeg2": "9"
    "video.av1": "10"
    "video.other": "11"
    "default": "11"

  audio_codec:
    "audio.alac": "8"
    "audio.aac": "9"
    "audio.ape": "10"
    "audio.truehd_atmos": "11"
    "audio.ddp": "12"
    "audio.ac3": "13"
    "audio.lpcm": "14"
    "audio.truehd": "15"
    "audio.dtsx": "16"
    "audio.dts_hd_ma": "17"
    "audio.dts": "18"
    "audio.m4a": "19"
    "audio.wav": "20"
    "audio.mp3": "21"
    "audio.flac": "22"
    "audio.other": "23"
    "default": "23"

  resolution:
    "resolution.r480p": "5"
    "resolution.r720p": "6"
    "resolution.r1080p": "7"
    "resolution.r2160p": "8"
    "resolution.r4320p": "9"
    "resolution.other": "10"
    "default": "10"

  team:
    "team.hds": "1"
    "team.chd": "2"
    "team.mysilu": "3"
    "team.wiki": "4"
    "team.other": "5"
    "team.rain": "6"
    "team.rainweb": "7"
    "team.tangweb": "8"
    "team.tangpt": "9"
    "default": "5"

  tag:
    "tag.特效": "9"
    "tag.杜比": "8"
    "tag.粤语": "10"
    "tag.DIY": "4"
    "tag.国语": "5"
    "tag.中字": "6"
    "tag.HDR": "7"
    "tag.Remux": "20"
    "tag.合并": "19"
    "tag.超分": "17"
    "tag.大包": "16"
    "tag.完结": "14"
    "tag.分集": "13"
    "tag.英字": "12"
    "tag.韩剧": "11"
    "default": null
